sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
    role_admin: ROLE_ADMIN
    role_super_admin: ROLE_SUPER_ADMIN
  title: 'Admin'
  title_logo: /bundles/pushwordcore/logo.svg
  dashboard:
    blocks:
    #- { type: sonata.admin.block.admin_list, position: left }
    groups:
      app.admin.group.page:
        label: admin.label.content
        label_catalogue: messages
        items:
          - pushword.admin.page
          - pushword.admin.media
      app.admin.group.static:
        label: admin.label.manage
        label_catalogue: messages
        icon: '<i class="fa fa-bolt"></i>'
        items:
          - route: pushword_page_scanner
            label: admin.label.check_content
          - route: piedweb_static_generate
            label: admin.label.update

      app.admin.group.setting:
        label: admin.label.params
        label_catalogue: messages
        icon: '<i class="fa fa-wrench"></i>'
        items:
          - pushword.admin.user
          - route: pushword_template_editor_list
            label: admin.label.theme
            roles:
              - ROLE_PIEDWEB_ADMIN_THEME

  options:
    lock_protection: true
  templates:
    layout: '@pwAdmin/layout.html.twig'
    knp_menu_template: '@pwAdmin/Menu/menu.html.twig'
    user_block: '@pwAdmin/user_block.html.twig'

sonata_doctrine_orm_admin:
  templates:
    form:
      - '@pwAdmin/Form/sd_form_admin_fields.html.twig'

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]

    sonata.admin.block.search_result:
      contexts: [admin]
