services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $mediaClass: "%pw.entity_media%"
      $pageClass: "%pw.entity_page%"
      $userClass: "%pw.entity_user%"

  Pushword\Admin\:
    resource: '../../src/'
    exclude:
        - '../../src/DependencyInjection/'
        - '../../src/FormField/'
        - '../../src/Resources/'
        - '../../src/config/'

  #Sonata\AdminBundle\Bridge\Exporter\AdminExporter:
  #
