services:
  # ---
  # Page
  # ---

  pushword.admin.page_menu:
        class: Pushword\Admin\Menu\PageMenuProvider
        autowire: true
        autoconfigure: true
        tags:
            - { name: knp_menu.menu_builder, method: getMenu, alias: page_admin_menu }

  #Sonata\AdminBundle\Bridge\Exporter\AdminExporter:
  #  autowire: true

  Pushword\Admin\PageAdminInterface:
    class: Pushword\Admin\PageAdmin
    autowire: true
    arguments:
      - ~
      - "%pw.entity_page%"
      - Pushword\Admin\PageCRUDControllerInterface
    tags:
      - { name: sonata.admin, manager_type: orm, label: admin.label.page }
    calls:
      - [setTemplate, [list, "@@pwAdmin/CRUD/mosaic.html.twig"]]
      - [setTemplate, [show, "@@pwAdmin/page/page_show.html.twig"]]
      - [setTemplate, [edit, "@@pwAdmin/page/page_edit.html.twig"]]
      - [setTemplate, [preview, "@@pwAdmin/page/preview.html.twig"]]
      - [setMediaClass, ["%pw.entity_media%"]]
      - [setUserClass, ["%pw.entity_user%"]]
      - [setPageClass, ["%pw.entity_page%"]]
    public: true

  Pushword\Admin\PageCRUDControllerInterface:
    class: Pushword\Admin\PageCRUDController
    autowire: true
    autoconfigure: true
    tags: ["controller.service_arguments"]

  # ---
  # Others
  # ---

  Pushword\Admin\MediaAdminInterface:
    alias: pushword.admin.media

  pushword.admin.media:
    class: Pushword\Admin\MediaAdmin
    arguments: [~, "%pw.entity_media%", ~]
    autowire: true
    calls:
      - [setTemplate, [list, "@@pwAdmin/CRUD/mosaic.html.twig"]]
      - [setTemplate, [short_object_description, "@@pwAdmin/media/short_object_description.html.twig"]]
      - [setPageClass, ["%pw.entity_page%"]]
      - [setMediaClass, ["%pw.entity_media%"]]
    tags:
      - { name: sonata.admin, manager_type: orm, label: admin.label.media, persist_filters: true }

  Pushword\Admin\UserAdminInterface:
    alias: pushword.admin.user

  pushword.admin.user:
    class: Pushword\Admin\UserAdmin
    autowire: true
    arguments: [~, "%pw.entity_user%", ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: admin.label.user }
    public: true
    calls:
      - [setUserClass, ["%pw.entity_user%"]]
