pushword_admin_dashboard:
  path: /admin/dashboard
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: admin_page_list

admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

pushword_markdown_cheatsheet:
  path: /admin/markdown-cheatsheet
  methods: [GET, HEAD]
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '@pwAdmin/markdown_cheatsheet.html.twig'

cheatsheetEditRoute:
  path: /admin/cheatsheet
  methods: [GET, HEAD]
  controller: \Pushword\Admin\PageCheatSheetController::cheatsheet
  defaults:
    template: '@pwAdmin/markdown_cheatsheet.html.twig'

# controllers:
#     resource:
#         path: ./Controller/
#         namespace: Pushword\Admin
#     type: attribute
